# Robot
input_sources:
  camera: # A name to identify the input source
    type: pointcloud 
    topic: /d435/depth/color/points
    queue_size: 5
    publish_on_update: true # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect
      
map_frame_id: world
robot_base_frame_id: base_footprint
sensor_frame_id: d435_depth_optical_frame
robot_pose_with_covariance_topic: "/pose" # Leaving this empty skipps pose covariance updates.
robot_pose_cache_size: 200
track_point_frame_id: world
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
min_update_rate: 2.0
time_tolerance: 0.5
sensor_processor/ignore_points_above: 0.4
robot_motion_map_update/covariance_scale_translation_x: 0.0
robot_motion_map_update/covariance_scale_translation_y: 0.0
robot_motion_map_update/covariance_scale_translation_z: 0.0
robot_motion_map_update/covariance_scale_rotation_x: 0.0
robot_motion_map_update/covariance_scale_rotation_y: 0.0
robot_motion_map_update/covariance_scale_rotation_z: 0.0

# Map
length_in_x: 6.0
length_in_y: 6.0
position_x: 0.0
position_y: 0.0
resolution: 0.5
min_variance: 0.0001
max_variance: 0.05
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.01
fused_map_publishing_rate: 2.0
enable_skip_lower_points: true
scanning_duration: 0.01
remove_penetrated_points_rate: 5.0
enable_visibility_cleanup: false
visibility_cleanup_rate: 1.0
scanning_duration: 1.0
