# Robot
input_sources:
  camera: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /d435/depth/color/points
    queue_size: 1
    publish_on_update: true # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect
map_frame_id: world
sensor_frame_id: d435_depth_optical_frame
robot_base_frame_id: base_footprint
robot_pose_with_covariance_topic: /pose
robot_pose_cache_size: 200
track_point_frame_id: world
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0

# Map
length_in_x: 10.0
length_in_y: 10.0
position_x: 0.0
position_y: 0.0
resolution: 0.05  # 0.01
min_variance: 0.000009
max_variance: 0.01
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
