gpg_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50

gpg_camera_controller:
  type: position_controllers/JointPositionController
  joint: camera_joint

gpg_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'wheel_left_joint'
  right_wheel: 'wheel_right_joint'
  publish_rate: 50
  pose_covariance_diagonal: [0.1, 0.001, 0.001, 0.001, 0.001, 0.3]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_footprint

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.1   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # rad/s^2
